//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Габитов_Михаил_Маратович_9.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class auction_gabitovEntities1 : DbContext
    {
        private static auction_gabitovEntities1 _context;

        public auction_gabitovEntities1()
            : base("name=auction_gabitovEntities1")
        {
        }
    
        public static auction_gabitovEntities1 GetContext()
        {
            if(_context == null)
            {
                _context= new auction_gabitovEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<sell> sells { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<type_item> type_item { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
