//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Габитов_Михаил_Маратович_9.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.sells = new HashSet<sell>();
        }
    
        public int id_item { get; set; }
        public string name_item { get; set; }
        public int id_type { get; set; }
        public int year_release { get; set; }
        public string owner { get; set; }
        public System.DateTime date_admission { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
    
        public virtual type_item type_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sell> sells { get; set; }
    }
}
