//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Габитов_Михаил_Маратович_9.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell
    {
        public int id_sale { get; set; }
        public int id_item { get; set; }
        public System.DateTime date_trade { get; set; }
        public double start_prise { get; set; }
        public double last_price { get; set; }
        public string sign_sale { get; set; }
        public string surname { get; set; }
    
        public virtual item item { get; set; }
    }
}
